server:
  port: 8083

# mybaits-plus配置
mybatis-plus:
  # 打开 Mybatis的二级缓存
  configuration:
    cache-enabled: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/**/*apper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1qaz!QAZ
    url: jdbc:mysql://localhost:3306/lh?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true

